CREATE DATABASE SAMPLEDB;
USE SAMPLEDB;
CREATE TABLE TBLEMPLOYEE(ID INT,NAME NVARCHAR(200));

SELECT * FROM TBLEMPLOYEE;
SELECT ID FROM TBLEMPLOYEE;
SELECT ID,NAME FROM TBLEMPLOYEE;
INSERT INTO TBLEMPLOYEE(ID,NAME) VALUES(1,'VIKASH');
INSERT INTO TBLEMPLOYEE VALUES(2,'RAHUL');
INSERT INTO TBLEMPLOYEE VALUES(3,'RAKESH'),(4,'RAMESH');
INSERT INTO TBLEMPLOYEE VALUES(5,'RAHUL');

TRUNCATE TABLE TBLEMPLOYEE;
DELETE FROM TBLEMPLOYEE;


DELETE FROM  TBLEMPLOYEE WHERE ID=5;

ALTER TABLE TBLEMPLOYEE ADD GENDER VARCHAR(1)

UPDATE TBLEMPLOYEE SET GENDER='M';
SELECT * FROM TBLEMPLOYEE;

INSERT INTO TBLEMPLOYEE VALUES(5,'RESHMA','M'),(6,'ANVI','M');
UPDATE TBLEMPLOYEE SET GENDER='F' WHERE ID=5;

SELECT * FROM TBLEMPLOYEE WHERE NAME LIKE 'A'; -- IT WILL BEHAVE AS EQUAL
SELECT * FROM TBLEMPLOYEE WHERE NAME LIKE '%A%';
SELECT * FROM TBLEMPLOYEE WHERE NAME LIKE '%A'; -- STARING WITH ANYTHING BUT IN THE END HAVE A
SELECT * FROM TBLEMPLOYEE WHERE NAME LIKE 'A%'; -- STARING WITH A BUT IN THE END HAVE ANYTHING

UPDATE TBLEMPLOYEE SET GENDER='F' WHERE NAME LIKE 'A%';

DROP TABLE TBLEMPLOYEE

CREATE TABLE TBLEMPLOYEE(ID INT IDENTITY(1,1),NAME NVARCHAR(200),GENDER VARCHAR(1));

INSERT INTO TBLEMPLOYEE VALUES('RAKESH','M'),('RAMESH','M');
INSERT INTO TBLEMPLOYEE VALUES('SHIVANI','F'),('ANJALI','F');

DELETE TBLEMPLOYEE
TRUNCATE TABLE TBLEMPLOYEE

CREATE TABLE DEPARTMENT(ID INT IDENTITY(1,1),DEPARTMENTNAME NVARCHAR(200) )

INSERT INTO DEPARTMENT VALUES('ADMIN'),('IT'),('SALES'),('SUPPORT');
SELECT * FROM DEPARTMENT;
SELECT * FROM TBLEMPLOYEE;
SELECT * FROM DEPARTMENT WHERE ID IN (SELECT DEPID FROM TBLEMPLOYEE);
SELECT * FROM DEPARTMENT WHERE ID IN (1,2,3,4);
SELECT * FROM DEPARTMENT WHERE ID NOT IN (1,2);


	

